---


 - name: packae installtion
   package:
      name: "{{package_name}}"
      state: present
   when: ansible_os_family == 'Debian'


 - name: manage service
   service:
      name: "{{package_name}}"
      state: present
      enabled: true
      when: ansible_os_family == 'Debian'

