
- name: appserver management
  hosts: appserver
  remote_user: ec2-user
  gather_facts: true
  become: true

  roles:
  - webserver


- name: local changes
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  roles:
  - users
